[package]
name = "my_binary"
version = "0.1.0"
authors = ["nawaz"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
my_library = { path = "../my_library"}